{"name": "test_login_failed_invalid_data[case0]", "status": "passed", "parameters": [{"name": "case", "value": "{'user': '', 'passwd': 'python', 'check': '请输入手机号'}"}], "start": 1599055533157, "stop": 1599055534769, "uuid": "77565243-7bf5-4b45-b879-7dcdf16a17b5", "historyId": "f0bfd36e151bd6809e3bea92a4f95e89", "testCaseId": "98e067a681f547a2e44e78c948720b9e", "fullName": "TestCases.test_login.TestLogin#test_login_failed_invalid_data", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "CY-20190809JTFQ"}, {"name": "thread", "value": "5776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}