{"name": "test_login_failed_invalid_data[case2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '请输入正确的手机号' == '请输入手机号'\n  - 请输入手机号\n  + 请输入正确的手机号\n  ?    +++", "trace": "self = <TestCases.test_login.TestLogin object at 0x0000020B9FC49198>\ncase = {'check': '请输入手机号', 'passwd': 'python', 'user': '1868472055'}\nback_login = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"790aeb4011e5dcb3091bfb152321d676\")>\n\n    @pytest.mark.parametrize(\"case\",td.invalid_data)\n    def test_login_failed_invalid_data(self,case,back_login):\n        LoginPage(back_login).login(case[\"user\"], case[\"passwd\"])\n>       assert LoginPage(back_login).get_error_msg_from_login_area() == case[\"check\"]\nE       AssertionError: assert '请输入正确的手机号' == '请输入手机号'\nE         - 请输入手机号\nE         + 请输入正确的手机号\nE         ?    +++\n\nTestCases\\test_login.py:28: AssertionError"}, "parameters": [{"name": "case", "value": "{'user': '1868472055', 'passwd': 'python', 'check': '请输入手机号'}"}], "start": 1599055538271, "stop": 1599055540844, "uuid": "bb43782c-f215-44e9-b276-9efbbaefd2f4", "historyId": "e60344e31024accddf6073cc86c6051a", "testCaseId": "98e067a681f547a2e44e78c948720b9e", "fullName": "TestCases.test_login.TestLogin#test_login_failed_invalid_data", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "CY-20190809JTFQ"}, {"name": "thread", "value": "5776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}