{"name": "test_login_failed_invalid_data[case3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '请输入正确的手机号' == '请输入手机号'\n  - 请输入手机号\n  + 请输入正确的手机号\n  ?    +++", "trace": "self = <TestCases.test_login.TestLogin object at 0x0000020B9FC58DD8>\ncase = {'check': '请输入手机号', 'passwd': 'python', 'user': '186847205531'}\nback_login = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"790aeb4011e5dcb3091bfb152321d676\")>\n\n    @pytest.mark.parametrize(\"case\",td.invalid_data)\n    def test_login_failed_invalid_data(self,case,back_login):\n        LoginPage(back_login).login(case[\"user\"], case[\"passwd\"])\n>       assert LoginPage(back_login).get_error_msg_from_login_area() == case[\"check\"]\nE       AssertionError: assert '请输入正确的手机号' == '请输入手机号'\nE         - 请输入手机号\nE         + 请输入正确的手机号\nE         ?    +++\n\nTestCases\\test_login.py:28: AssertionError"}, "parameters": [{"name": "case", "value": "{'user': '186847205531', 'passwd': 'python', 'check': '请输入手机号'}"}], "start": 1599055541744, "stop": 1599055544034, "uuid": "696663b4-b883-4c02-8441-87b37ca456d5", "historyId": "7b7b379e8ec7b1b6556bcf518822b40d", "testCaseId": "98e067a681f547a2e44e78c948720b9e", "fullName": "TestCases.test_login.TestLogin#test_login_failed_invalid_data", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "CY-20190809JTFQ"}, {"name": "thread", "value": "5776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}