{"name": "test_casesss", "status": "broken", "statusDetails": {"message": "NameError: name 'aaa' is not defined", "trace": "self = <test_2_abc.TestABC object at 0x00000269A8A03860>\n\n    def test_casesss(self):\n>       print(aaa)\nE       NameError: name 'aaa' is not defined\n\ntest_2_abc.py:55: NameError"}, "start": 1596630454605, "stop": 1596630454606, "uuid": "593b34ce-8f9f-4367-9bfc-bdb450203234", "historyId": "ae99bc624bbac66f5f0cd925169d24d1", "testCaseId": "8ca5ad255e3b036fcc93b8971f4acf71", "fullName": "test_2_abc.TestABC#test_casesss", "labels": [{"name": "suite", "value": "test_2_abc"}, {"name": "subSuite", "value": "TestABC"}, {"name": "host", "value": "CY-20190809JTFQ"}, {"name": "thread", "value": "14232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_2_abc"}]}