{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_2_abc.TestABC object at 0x0000022FC8C0F400>\n\n    def test_fail(self):\n>       assert False\nE       assert False\n\ntest_2_abc.py:37: AssertionError"}, "start": 1597062566188, "stop": 1597062566188, "uuid": "919bc04c-38fe-47e6-89ef-abc8da4b6bc8", "historyId": "8be2222459f23a81141e9e3625abb199", "testCaseId": "9befbc794e34ef2873a72402902b9a45", "fullName": "test_2_abc.TestABC#test_fail", "labels": [{"name": "tag", "value": "nmb"}, {"name": "tag", "value": "py30"}, {"name": "suite", "value": "test_2_abc"}, {"name": "subSuite", "value": "TestABC"}, {"name": "host", "value": "CY-20190809JTFQ"}, {"name": "thread", "value": "5632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_2_abc"}]}